name: build rucio-client docker image
on:
  push:
    branches:
      - "*"
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    name: build
    steps:
      - uses: actions/checkout@master
      - name: Extract tag name
        shell: bash
        run: echo "##[set-output name=imagetag;]$(echo ${GITHUB_REF##*/})"
        id: extract_tag_name
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: sslhep/rucio-client:${{ steps.extract_tag_name.outputs.imagetag }}